"""
Codex Alpha Computational Framework
Graph Builder Module

This module builds a relational graph from Gaia DR3 anomalous sources.

Each node represents an astrophysical source.
Each edge represents multidimensional similarity between sources.

The goal is to move from isolated anomaly detection toward relational
and emergent structure exploration.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import StandardScaler


INPUT_PATH = Path("results/gaia_dr3_emergent_structures.csv")
NODES_OUTPUT_PATH = Path("results/gaia_dr3_graph_nodes.csv")
EDGES_OUTPUT_PATH = Path("results/gaia_dr3_graph_edges.csv")


FEATURE_COLUMNS = [
    "ra",
    "dec",
    "parallax",
    "pmra",
    "pmdec",
    "phot_g_mean_mag",
    "phot_bp_mean_mag",
    "phot_rp_mean_mag",
    "bp_rp",
    "radial_velocity",
]


def build_gaia_anomaly_graph(
    input_path: Path = INPUT_PATH,
    nodes_output_path: Path = NODES_OUTPUT_PATH,
    edges_output_path: Path = EDGES_OUTPUT_PATH,
    n_neighbors: int = 5,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Build a nearest-neighbor graph from Gaia DR3 anomalous sources.

    Parameters
    ----------
    input_path:
        Input CSV generated by emergent structure detection.

    nodes_output_path:
        Output CSV containing graph nodes.

    edges_output_path:
        Output CSV containing graph edges.

    n_neighbors:
        Number of nearest neighbors connected to each node.

    Returns
    -------
    tuple[pandas.DataFrame, pandas.DataFrame]
        Nodes dataframe and edges dataframe.
    """

    if not input_path.exists():
        raise FileNotFoundError(f"Input file not found: {input_path}")

    df = pd.read_csv(input_path)

    required = set(FEATURE_COLUMNS + ["SOURCE_ID", "anomaly_score"])
    missing = required - set(df.columns)

    if missing:
        raise ValueError(f"Missing required columns: {missing}")

    data = df.copy()

    features = data[FEATURE_COLUMNS].replace([np.inf, -np.inf], np.nan)
    features = features.dropna()

    data = data.loc[features.index].copy().reset_index(drop=True)

    if len(data) <= n_neighbors:
        raise ValueError(
            f"Not enough sources ({len(data)}) for n_neighbors={n_neighbors}."
        )

    scaler = StandardScaler()
    x_scaled = scaler.fit_transform(features)

    neighbors = NearestNeighbors(
        n_neighbors=n_neighbors + 1,
        metric="euclidean",
    )

    neighbors.fit(x_scaled)

    distances, indices = neighbors.kneighbors(x_scaled)

    nodes = data.copy()
    nodes["node_id"] = nodes.index

    edge_rows = []

    for source_idx, neighbor_row in enumerate(indices):
        for position, target_idx in enumerate(neighbor_row[1:], start=1):
            distance = distances[source_idx][position]

            edge_rows.append(
                {
                    "source_node": source_idx,
                    "target_node": int(target_idx),
                    "source_id": nodes.loc[source_idx, "SOURCE_ID"],
                    "target_id": nodes.loc[int(target_idx), "SOURCE_ID"],
                    "feature_distance": float(distance),
                    "similarity_weight": float(1.0 / (distance + 1e-12)),
                }
            )

    edges = pd.DataFrame(edge_rows)

    nodes_output_path.parent.mkdir(parents=True, exist_ok=True)

    nodes.to_csv(nodes_output_path, index=False)
    edges.to_csv(edges_output_path, index=False)

    print("\nGraph construction completed.")
    print(f"Nodes: {len(nodes)}")
    print(f"Edges: {len(edges)}")

    print(f"\nGraph nodes saved to: {nodes_output_path}")
    print(f"Graph edges saved to: {edges_output_path}")

    print("\nTop 10 strongest graph connections:")
    print(
        edges.sort_values(
            by="similarity_weight",
            ascending=False,
        ).head(10)
    )

    return nodes, edges


if __name__ == "__main__":
    build_gaia_anomaly_graph()
