"""
Codex Alpha Computational Framework
Pipeline Report Generator
"""

from __future__ import annotations

from datetime import datetime, UTC
from pathlib import Path

import pandas as pd


RESULTS_DIR = Path("results")

ANOMALY_RESULTS = RESULTS_DIR / "gaia_dr3_anomaly_results.csv"
FEATURE_CONTRIBUTIONS = RESULTS_DIR / "gaia_dr3_feature_contributions.csv"
ANOMALY_CLUSTERS = RESULTS_DIR / "gaia_dr3_anomaly_clusters.csv"
EMERGENT_STRUCTURES = RESULTS_DIR / "gaia_dr3_emergent_structures.csv"
GRAPH_NODES = RESULTS_DIR / "gaia_dr3_graph_nodes.csv"
GRAPH_EDGES = RESULTS_DIR / "gaia_dr3_graph_edges.csv"
GRAPH_CENTRALITY = RESULTS_DIR / "gaia_dr3_graph_centrality.csv"

REPORT_OUTPUT = RESULTS_DIR / "gaia_dr3_pipeline_report.md"


def load_csv(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"Required pipeline output not found: {path}")

    return pd.read_csv(path)


def dataframe_to_markdown_table(
    df: pd.DataFrame,
    columns: list[str],
    max_rows: int = 10,
) -> str:
    """
    Convert selected dataframe columns to a Markdown table
    without scientific notation.
    """

    available_columns = [col for col in columns if col in df.columns]

    if not available_columns:
        return "_No matching columns available._"

    subset = df[available_columns].head(max_rows).copy()

    for column in subset.columns:

        if "SOURCE_ID" in column:
            subset[column] = subset[column].astype(str)

        elif subset[column].dtype.kind in {"f"}:
            subset[column] = subset[column].map(lambda x: f"{x:.6f}")

    return subset.to_markdown(index=False)


def generate_pipeline_report(
    output_path: Path = REPORT_OUTPUT,
) -> None:

    anomalies = load_csv(ANOMALY_RESULTS)
    feature_contributions = load_csv(FEATURE_CONTRIBUTIONS)
    clusters = load_csv(ANOMALY_CLUSTERS)
    emergent = load_csv(EMERGENT_STRUCTURES)
    graph_nodes = load_csv(GRAPH_NODES)
    graph_edges = load_csv(GRAPH_EDGES)
    graph_centrality = load_csv(GRAPH_CENTRALITY)

    anomaly_count = len(
        anomalies[anomalies["anomaly_label"] == -1]
    )

    total_count = len(anomalies)

    cluster_summary = (
        clusters.groupby("anomaly_cluster")
        .agg(
            count=("SOURCE_ID", "count"),
            mean_anomaly_score=("anomaly_score", "mean"),
            max_anomaly_score=("anomaly_score", "max"),
        )
        .reset_index()
        .sort_values(
            by="mean_anomaly_score",
            ascending=False,
        )
    )

    top_anomalies_table = dataframe_to_markdown_table(
        anomalies,
        [
            "SOURCE_ID",
            "anomaly_rank",
            "anomaly_score",
            "anomaly_label",
            "ra",
            "dec",
            "parallax",
            "radial_velocity",
        ],
    )

    feature_contribution_table = dataframe_to_markdown_table(
        feature_contributions,
        [
            "SOURCE_ID",
            "anomaly_rank",
            "anomaly_score",
            "dominant_anomaly_feature",
            "dominant_feature_zscore",
        ],
    )

    emergent_structures_table = dataframe_to_markdown_table(
        emergent,
        [
            "SOURCE_ID",
            "anomaly_score",
            "local_density_score",
            "mean_neighbor_distance",
            "emergent_structure_rank",
        ],
    )

    graph_centrality_table = dataframe_to_markdown_table(
        graph_centrality,
        [
            "SOURCE_ID",
            "structural_rank",
            "degree_centrality",
            "betweenness_centrality",
            "closeness_centrality",
            "weighted_degree",
            "structural_importance_score",
        ],
    )

    report = f"""
# Gaia DR3 Full Pipeline Report

Generated on: {datetime.now(UTC).isoformat()}

---

# Overview

This report was automatically generated by the Codex Alpha Computational Framework.

The pipeline analyzes a real ESA Gaia DR3 sample dataset and performs:

1. multidimensional anomaly detection
2. feature contribution analysis
3. anomaly clustering
4. emergent structure detection
5. relational graph construction
6. graph centrality analysis
7. exploratory visualization generation

The current analysis is exploratory and does not constitute a claim of new physical discovery.

---

# Dataset Summary

Total analyzed sources: {total_count}

Detected anomalous sources: {anomaly_count}

---

# Top Ranked Anomalous Sources

{top_anomalies_table}

---

# Top Feature Contribution Results

{feature_contribution_table}

---

# Anomaly Cluster Summary

{cluster_summary.to_markdown(index=False)}

---

# Top Emergent Local Structure Candidates

{emergent_structures_table}

---

# Relational Graph Summary

Graph nodes: {len(graph_nodes)}

Graph edges: {len(graph_edges)}

The relational graph represents anomalous Gaia DR3 sources as nodes and multidimensional similarity relationships as edges.

---

# Top Structurally Important Sources

{graph_centrality_table}

---

# Generated Output Files

- results/gaia_dr3_anomaly_results.csv
- results/gaia_dr3_feature_contributions.csv
- results/gaia_dr3_anomaly_clusters.csv
- results/gaia_dr3_emergent_structures.csv
- results/gaia_dr3_graph_nodes.csv
- results/gaia_dr3_graph_edges.csv
- results/gaia_dr3_graph_centrality.csv
- results/gaia_dr3_anomaly_sky_plot.png
- results/gaia_dr3_relational_graph.png
- results/gaia_dr3_pipeline_report.md

---

# Interpretation Note

Higher anomaly scores indicate statistically rarer sources within the analyzed multidimensional feature space.

Higher local density scores indicate anomalous sources located near other anomalous sources in the standardized multidimensional feature space.

Higher structural importance scores indicate sources that occupy more relevant positions inside the relational graph.

These values are exploratory computational indicators and require additional astrophysical validation before any physical interpretation.
"""

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    output_path.write_text(
        report.strip() + "\n",
        encoding="utf-8",
    )

    print(
        f"Pipeline report generated: {output_path}"
    )


if __name__ == "__main__":
    generate_pipeline_report()
